routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TempMapColumnsController;
use App\Http\Controllers\SetTimeFlagsContoller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TempsController;
use App\Http\Controllers\SensorsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::prefix('qc')->group(function () {
    Route::resource('temp_map_columns', TempMapColumnsController::class);
    Route::resource('temps', TempsController::class);
    Route::resource('sensors', SensorsController::class);
    Route::get('temps/excel/{date}', [TempsController::class, 'excel'])->name('temps.excel');
    Route::resource('set_time_flags', SetTimeFlagsContoller::class);
    Route::get('set_time_flags/clone/{id}', [SetTimeFlagsContoller::class, 'clone'])->name('set_time_flags.clone');
});
Route::resource('user', UserController::class);


Route::group(['namespace' => 'App\Http\Controllers'], function()
{   
    /**
     * Home Routes
     */
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::group(['middleware' => ['guest']], function() {
        /**
         * Register Routes
         */
        Route::get('/register', 'RegisterController@show')->name('register.show');
        Route::post('/register', 'RegisterController@register')->name('register.perform');

        /**
         * Login Routes
         */
        Route::get('/login', 'LoginController@show')->name('login.show');
        Route::post('/login', 'LoginController@login')->name('login.perform');

    });

    Route::group(['middleware' => ['auth']], function() {
        /**
         * Logout Routes
         */
        Route::get('/logout', 'LogoutController@perform')->name('logout.perform');
    });
});

app/Models/Sensor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sensor extends Model
{
    use HasFactory;

    protected $fillable = ['code','type', 'gateway','name','note','status','conditions','conditions2','displaycond','show','seq','displayname','coil'];

    public function tempds()
    {
        return $this->hasMany('App\Models\SensorData', 'sensor_id');
    }

}

app/Http/Controllers/SensorsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Sensor;

class SensorsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $sensors = Sensor::orderBy('seq')->paginate($perPage);
        } else {
            $sensors = Sensor::orderBy('seq')->paginate($perPage);
        }

        return view('qc.sensors.index', compact('sensors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $sensor = Sensor::findOrFail($id);

        return view('qc.sensors.view', compact('sensor'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sensor = Sensor::findOrFail($id);

        return view('qc.sensors.edit', compact('sensor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $requestData = $request->all();

        $sensor = Sensor::findOrFail($id);
        $sensor->update($requestData);

        return redirect('qc/sensors')->with('flash_message', 'Dep updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/qc/sensors/create.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Column Map กับ Excel Scada') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('temp_map_columns.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('สร้าง Column Map') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('temp_map_columns.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('ชื่อ') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="displayname" class="col-md-3 col-form-label text-md-right">{{ __('Displayname') }}</label>

                                <div class="col-md-6">
                                    <input id="displayname" type="text" class="form-control @error('displayname') is-invalid @enderror"
                                        name="displayname" value="" required autofocus>

                                    @error('displayname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="mapcolumn" class="col-md-3 col-form-label text-md-right">{{ __('Map Column') }}</label>

                                <div class="col-md-6">
                                    <input id="mapcolumn" type="text" class="form-control @error('mapcolumn') is-invalid @enderror"
                                        name="mapcolumn" value="" required autofocus>

                                    @error('mapcolumn')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="typecolumn" class="col-md-3 col-form-label text-md-right">{{ __('Type Column') }}</label>

                                <div class="col-md-6">
                                    <input id="typecolumn" type="text" class="form-control @error('typecolumn') is-invalid @enderror"
                                        name="typecolumn" value="" required autofocus>

                                    @error('typecolumn')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="show" class="col-md-3 col-form-label text-md-right">{{ __('Show') }}</label>

                                <div class="col-md-6">
                                    {{ Form::select('show', array('Yes'=>'Yes','No'=>'No'), 'Yes', ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}
                                    

                                    @error('show')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="seq" class="col-md-3 col-form-label text-md-right">{{ __('Seq') }}</label>

                                <div class="col-md-6">
                                    <input id="seq" type="number" class="form-control @error('typecolumn') is-invalid @enderror"
                                        name="seq" value="1" required autofocus>

                                    @error('seq')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="conditions" class="col-md-3 col-form-label text-md-right">{{ __('Condition') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions" type="text" class="form-control @error('conditions') is-invalid @enderror"
                                        name="conditions" value="" autofocus>

                                    @error('conditions')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="conditions2" class="col-md-3 col-form-label text-md-right">{{ __('Condition 2') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions2" type="text" class="form-control @error('conditions2') is-invalid @enderror"
                                        name="conditions2" value="" autofocus>

                                    @error('conditions2')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-6">
                                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror"
                                        name="status" value="Active" autofocus>

                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('สร้าง') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qc/sensors/edit.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Column Map กับ Excel Scada') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('sensors.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แก้ไข Sensor กับ RTE Scada') }}</div>

                    <div class="card-body">
                        <form action="{{ route('sensors.update', $sensor->id) }}" method="POST">
                            @csrf

                            @method('PUT')
                            <div class="form-group row">
                                <label for="code" class="col-md-3 col-form-label text-md-right">{{ __('Code') }}</label>

                                <div class="col-md-6">
                                    <input id="code" type="text" class="form-control @error('code') is-invalid @enderror"
                                        name="code" value="{{ $sensor->code }}" required autocomplete="code" autofocus>

                                    @error('code')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="type" class="col-md-3 col-form-label text-md-right">{{ __('type') }}</label>

                                <div class="col-md-6">
                                    <input id="type" type="text" class="form-control @error('type') is-invalid @enderror"
                                        name="type" value="{{ $sensor->type }}" required autocomplete="type" autofocus>

                                    @error('type')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="gateway" class="col-md-3 col-form-label text-md-right">{{ __('gateway') }}</label>

                                <div class="col-md-6">
                                    <input id="gateway" type="text" class="form-control @error('gateway') is-invalid @enderror"
                                        name="gateway" value="{{ $sensor->gateway }}" required autocomplete="gateway" autofocus>

                                    @error('gateway')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('ชื่อ') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ $sensor->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="displayname" class="col-md-3 col-form-label text-md-right">{{ __('Display Name') }}</label>

                                <div class="col-md-6">
                                    <input id="displayname" type="text" class="form-control @error('displayname') is-invalid @enderror"
                                        name="displayname" value="{{ $sensor->displayname }}" required autocomplete="displayname" autofocus>

                                    @error('displayname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="coil" class="col-md-3 col-form-label text-md-right">{{ __('Coil') }}</label>

                                <div class="col-md-6">
                                    <input id="coil" type="text" class="form-control @error('coil') is-invalid @enderror"
                                        name="coil" value="{{ $sensor->coil }}" required autocomplete="coil" autofocus>

                                    @error('coil')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="show" class="col-md-3 col-form-label text-md-right">{{ __('Show') }}</label>

                                <div class="col-md-6">
                                    {{ Form::select('show', array('Yes'=>'Yes','No'=>'No'), $sensor->show, ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}
                                    

                                    @error('show')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="seq" class="col-md-3 col-form-label text-md-right">{{ __('Seq') }}</label>

                                <div class="col-md-6">
                                    <input id="seq" type="number" class="form-control @error('typecolumn') is-invalid @enderror"
                                        name="seq" value="{{ $sensor->seq }}" required autofocus>

                                    @error('seq')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="conditions" class="col-md-3 col-form-label text-md-right">{{ __('Condition RED') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions" type="text" class="form-control @error('conditions') is-invalid @enderror"
                                        name="conditions" value="{{ $sensor->conditions }}" autofocus>

                                    @error('conditions')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="conditions2" class="col-md-3 col-form-label text-md-right">{{ __('Condition Yellow') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions2" type="text" class="form-control @error('conditions2') is-invalid @enderror"
                                        name="conditions2" value="{{ $sensor->conditions2 }}" autofocus>

                                    @error('conditions2')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="displaycond" class="col-md-3 col-form-label text-md-right">{{ __('Condition Display') }}</label>

                                <div class="col-md-6">
                                    <input id="displaycond" type="text" class="form-control @error('displaycond') is-invalid @enderror"
                                        name="displaycond" value="{{ $sensor->displaycond }}" autofocus>

                                    @error('displaycond')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-6">
                                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror"
                                        name="status" value="{{ $sensor->status }}" autofocus>

                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('แก้ไข') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qc/sensors/index.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Column Map กับ Excel Scada') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-success" href="{{ route('sensors.create') }}">สร้าง Sensor</a>
                    </div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                            <div class="pagination-wrapper"> {!! $sensors->render('vendor\pagination\bootstrap-4') !!} </div>
                   
                        <table class="table table-bordered">
                            <tr>
                                <th>ชื่อ</th>
                                <th>เงื่อนไข RED</th>
                                <th>เงื่อนไข Yellow</th>
                                <th>ลำดับ</th>
                                <th>แสดง</th>
                                <th></th>
                            </tr>
                            @foreach ($sensors as $sensor)
                                <tr>
                                    <td>{{ $sensor->displayname }} / {{ $sensor->coil }}</td>
                                    <td>{{ $sensor->conditions }}</td>
                                    <td>{{ $sensor->conditions2 }}</td>
                                    <td>{{ $sensor->seq }}</td>
                                    <td>{{ $sensor->show }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('sensors.show', $sensor->id) }}">แสดง</a>
                                        <a class="btn btn-primary" href="{{ route('sensors.edit', $sensor->id) }}">แก้ไข</a>
                                        <form action="{{ route('sensors.destroy', $sensor->id) }}" method="POST">

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">ลบ</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                         <div class="pagination-wrapper"> {!! $sensors->render('vendor\pagination\bootstrap-4') !!} </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection