routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TempMapColumnsController;
use App\Http\Controllers\SetTimeFlagsContoller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TempsController;
use App\Http\Controllers\SensorsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::prefix('qc')->group(function () {
    Route::resource('temp_map_columns', TempMapColumnsController::class);
    Route::resource('temps', TempsController::class);
    Route::resource('sensors', SensorsController::class);
    Route::get('temps/excel/{date}', [TempsController::class, 'excel'])->name('temps.excel');
    Route::resource('set_time_flags', SetTimeFlagsContoller::class);
    Route::get('set_time_flags/clone/{id}', [SetTimeFlagsContoller::class, 'clone'])->name('set_time_flags.clone');
});
Route::resource('user', UserController::class);


Route::group(['namespace' => 'App\Http\Controllers'], function()
{   
    /**
     * Home Routes
     */
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::group(['middleware' => ['guest']], function() {
        /**
         * Register Routes
         */
        Route::get('/register', 'RegisterController@show')->name('register.show');
        Route::post('/register', 'RegisterController@register')->name('register.perform');

        /**
         * Login Routes
         */
        Route::get('/login', 'LoginController@show')->name('login.show');
        Route::post('/login', 'LoginController@login')->name('login.perform');

    });

    Route::group(['middleware' => ['auth']], function() {
        /**
         * Logout Routes
         */
        Route::get('/logout', 'LogoutController@perform')->name('logout.perform');
    });
});

app/Models/TempMapColumn.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TempMapColumn extends Model
{
    use HasFactory;

    protected $fillable = [
        'name','displayname','mapcolumn','typecolumn',
        'conditions', 'conditions2', 'status','seq', 'show',
        'displaycond'
    ];

    public function tempds()
    {
        return $this->hasMany('App\Models\TempDataD', 'temp_map_column_id');
    }
}

app/Http/Controllers/TempMapColumnsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\TempMapColumn;

class TempMapColumnsController extends Controller
{
    public function __construct()
    {
        $this->middleware('isAdmin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $tempmapcolumns = TempMapColumn::orderBy('seq')->paginate($perPage);
        } else {
            $tempmapcolumns = TempMapColumn::orderBy('seq')->paginate($perPage);
        }

        return view('qc.temp_map_columns.index', compact('tempmapcolumns'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('qc.temp_map_columns.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $requestData = $request->all();

        TempMapColumn::create($requestData);

        return redirect('qc/temp_map_columns')->with('flash_message', 'TempMapColumn added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tempmapcolumn = TempMapColumn::findOrFail($id);

        return view('qc.temp_map_columns.view', compact('tempmapcolumn'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tempmapcolumn = TempMapColumn::findOrFail($id);

        return view('qc.temp_map_columns.edit', compact('tempmapcolumn'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $requestData = $request->all();

        $tempmapcolumn = TempMapColumn::findOrFail($id);
        $tempmapcolumn->update($requestData);

        return redirect('qc/temp_map_columns')->with('flash_message', 'Dep updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/qc/temp_map_columns/create.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Column Map กับ Excel Scada') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('temp_map_columns.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('สร้าง Column Map') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('temp_map_columns.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('ชื่อ') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="displayname" class="col-md-3 col-form-label text-md-right">{{ __('Displayname') }}</label>

                                <div class="col-md-6">
                                    <input id="displayname" type="text" class="form-control @error('displayname') is-invalid @enderror"
                                        name="displayname" value="" required autofocus>

                                    @error('displayname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="mapcolumn" class="col-md-3 col-form-label text-md-right">{{ __('Map Column') }}</label>

                                <div class="col-md-6">
                                    <input id="mapcolumn" type="text" class="form-control @error('mapcolumn') is-invalid @enderror"
                                        name="mapcolumn" value="" required autofocus>

                                    @error('mapcolumn')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="typecolumn" class="col-md-3 col-form-label text-md-right">{{ __('Type Column') }}</label>

                                <div class="col-md-6">
                                    <input id="typecolumn" type="text" class="form-control @error('typecolumn') is-invalid @enderror"
                                        name="typecolumn" value="" required autofocus>

                                    @error('typecolumn')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="show" class="col-md-3 col-form-label text-md-right">{{ __('Show') }}</label>

                                <div class="col-md-6">
                                    {{ Form::select('show', array('Yes'=>'Yes','No'=>'No'), 'Yes', ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}
                                    

                                    @error('show')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="seq" class="col-md-3 col-form-label text-md-right">{{ __('Seq') }}</label>

                                <div class="col-md-6">
                                    <input id="seq" type="number" class="form-control @error('typecolumn') is-invalid @enderror"
                                        name="seq" value="1" required autofocus>

                                    @error('seq')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="conditions" class="col-md-3 col-form-label text-md-right">{{ __('Condition') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions" type="text" class="form-control @error('conditions') is-invalid @enderror"
                                        name="conditions" value="" autofocus>

                                    @error('conditions')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            
                            <div class="form-group row">
                                <label for="conditions2" class="col-md-3 col-form-label text-md-right">{{ __('Condition 2') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions2" type="text" class="form-control @error('conditions2') is-invalid @enderror"
                                        name="conditions2" value="" autofocus>

                                    @error('conditions2')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-6">
                                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror"
                                        name="status" value="Active" autofocus>

                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('สร้าง') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qc/temp_map_columns/edit.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Column Map กับ Excel Scada') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('temp_map_columns.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แก้ไข Column Map กับ Excel Scada') }}</div>

                    <div class="card-body">
                        <form action="{{ route('temp_map_columns.update', $tempmapcolumn->id) }}" method="POST">
                            @csrf

                            @method('PUT')

                            <div class="form-group row">
                                <label for="name" class="col-md-3 col-form-label text-md-right">{{ __('ชื่อ') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                        name="name" value="{{ $tempmapcolumn->name }}" required autocomplete="name" autofocus>

                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="displayname" class="col-md-3 col-form-label text-md-right">{{ __('Displayname') }}</label>

                                <div class="col-md-6">
                                    <input id="displayname" type="text" class="form-control @error('displayname') is-invalid @enderror"
                                        name="displayname" value="{{ $tempmapcolumn->displayname }}" required autofocus>

                                    @error('displayname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="mapcolumn" class="col-md-3 col-form-label text-md-right">{{ __('Map Column') }}</label>

                                <div class="col-md-6">
                                    <input id="mapcolumn" type="text" class="form-control @error('mapcolumn') is-invalid @enderror"
                                        name="mapcolumn" value="{{ $tempmapcolumn->mapcolumn }}" required autofocus>

                                    @error('mapcolumn')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="displaycond" class="col-md-3 col-form-label text-md-right">{{ __('Display Column') }}</label>

                                <div class="col-md-6">
                                    <input id="displaycond" type="text" class="form-control @error('displaycond') is-invalid @enderror"
                                        name="displaycond" value="{{ $tempmapcolumn->displaycond }}" required autofocus>

                                    @error('displaycond')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="typecolumn" class="col-md-3 col-form-label text-md-right">{{ __('Type Column') }}</label>

                                <div class="col-md-6">
                                    <input id="typecolumn" type="text" class="form-control @error('typecolumn') is-invalid @enderror"
                                        name="typecolumn" value="{{ $tempmapcolumn->typecolumn }}" required autofocus>

                                    @error('typecolumn')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="show" class="col-md-3 col-form-label text-md-right">{{ __('Show') }}</label>

                                <div class="col-md-6">
                                    {{ Form::select('show', array('Yes'=>'Yes','No'=>'No'), $tempmapcolumn->show, ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}


                                    @error('show')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="seq" class="col-md-3 col-form-label text-md-right">{{ __('Seq') }}</label>

                                <div class="col-md-6">
                                    <input id="seq" type="number" class="form-control @error('typecolumn') is-invalid @enderror"
                                        name="seq" value="{{ $tempmapcolumn->seq }}" required autofocus>

                                    @error('seq')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="conditions" class="col-md-3 col-form-label text-md-right">{{ __('Condition RED') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions" type="text" class="form-control @error('conditions') is-invalid @enderror"
                                        name="conditions" value="{{ $tempmapcolumn->conditions }}" autofocus>

                                    @error('conditions')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="conditions2" class="col-md-3 col-form-label text-md-right">{{ __('Condition Yellow') }}</label>

                                <div class="col-md-6">
                                    <input id="conditions2" type="text" class="form-control @error('conditions2') is-invalid @enderror"
                                        name="conditions2" value="{{ $tempmapcolumn->conditions2 }}" autofocus>

                                    @error('conditions2')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-6">
                                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror"
                                        name="status" value="{{ $tempmapcolumn->status }}" autofocus>

                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('แก้ไข') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qc/temp_map_columns/index.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Column Map กับ Excel Scada') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-success" href="{{ route('temp_map_columns.create') }}">สร้าง Column Map</a>
                    </div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                            <div class="pagination-wrapper"> {!! $tempmapcolumns->render('vendor\pagination\bootstrap-4') !!} </div>
                   
                        <table class="table table-bordered">
                            <tr>
                                <th>ชื่อ</th>
                                <th>เงื่อนไข RED</th>
                                <th>เงื่อนไข Yellow</th>
                                <th>ลำดับ</th>
                                <th>แสดง</th>
                                <th></th>
                            </tr>
                            @foreach ($tempmapcolumns as $tempmapcolumn)
                                <tr>
                                    <td>{{ $tempmapcolumn->name }}</td>
                                    <td>{{ $tempmapcolumn->conditions }}</td>
                                    <td>{{ $tempmapcolumn->conditions2 }}</td>
                                    <td>{{ $tempmapcolumn->seq }}</td>
                                    <td>{{ $tempmapcolumn->show }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('temp_map_columns.show', $tempmapcolumn->id) }}">แสดง</a>
                                        <a class="btn btn-primary" href="{{ route('temp_map_columns.edit', $tempmapcolumn->id) }}">แก้ไข</a>
                                        <form action="{{ route('temp_map_columns.destroy', $tempmapcolumn->id) }}" method="POST">

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">ลบ</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                         <div class="pagination-wrapper"> {!! $tempmapcolumns->render('vendor\pagination\bootstrap-4') !!} </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/qc/temp_map_columns/view.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการประเภทกล่องแตก') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('temp_map_columns.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แสดงประเภทกล่องแตก') }}</div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>ชื่อ</th>
                                <td>{{ $tempmapcolumn->name }}</td>
                            </tr>
                            <tr>
                                <th>Displayname</th>
                                <td>{{ $tempmapcolumn->displayname }}</td>
                            </tr>
                            <tr>
                                <th>Map Column</th>
                                <td>{{ $tempmapcolumn->mapcolumn }}</td>
                            </tr>
                            <tr>
                                <th>Type Column</th>
                                <td>{{ $tempmapcolumn->typecolumn }}</td>
                            </tr>
                            <tr>
                                <th>Show</th>
                                <td> <div class="col-md-6">
                                    {{ Form::select('show', array('Yes'=>'Yes','No'=>'No'), $tempmapcolumn->show, ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}                                    
                            </tr>
                            <tr>
                                <th>Seq</th>
                                <td>{{ $tempmapcolumn->seq }}</td>
                            </tr>
                            <tr>
                                <th>Condition</th>
                                <td>{{ $tempmapcolumn->conditions }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>{{ $tempmapcolumn->status }}</td>
                            </tr>
                            
                            <tr>
                                <th>Action</th>
                                <td>
                                    <a class="btn btn-primary" href="{{ route('temp_map_columns.edit', $tempmapcolumn->id) }}">แก้ไข</a>
                                    <form action="{{ route('temp_map_columns.destroy', $tempmapcolumn->id) }}" method="POST">

                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">ลบ</button>
                                    </form>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection