routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TempMapColumnsController;
use App\Http\Controllers\SetTimeFlagsContoller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TempsController;
use App\Http\Controllers\SensorsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::prefix('qc')->group(function () {
    Route::resource('temp_map_columns', TempMapColumnsController::class);
    Route::resource('temps', TempsController::class);
    Route::resource('sensors', SensorsController::class);
    Route::get('temps/excel/{date}', [TempsController::class, 'excel'])->name('temps.excel');
    Route::resource('set_time_flags', SetTimeFlagsContoller::class);
    Route::get('set_time_flags/clone/{id}', [SetTimeFlagsContoller::class, 'clone'])->name('set_time_flags.clone');
});
Route::resource('user', UserController::class);


Route::group(['namespace' => 'App\Http\Controllers'], function()
{   
    /**
     * Home Routes
     */
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::group(['middleware' => ['guest']], function() {
        /**
         * Register Routes
         */
        Route::get('/register', 'RegisterController@show')->name('register.show');
        Route::post('/register', 'RegisterController@register')->name('register.perform');

        /**
         * Login Routes
         */
        Route::get('/login', 'LoginController@show')->name('login.show');
        Route::post('/login', 'LoginController@login')->name('login.perform');

    });

    Route::group(['middleware' => ['auth']], function() {
        /**
         * Logout Routes
         */
        Route::get('/logout', 'LogoutController@perform')->name('logout.perform');
    });
});

resources/views/qc/set_time_flags/clone.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Flag Time') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('set_time_flags.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('สร้าง Column Map') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('set_time_flags.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="temp_map_column_id" class="col-md-3 col-form-label text-md-right">{{ __('Sensor') }}</label>

                                <div class="col-md-6">
                                    {!! Form::select('temp_map_column_id', $tempmapcolumnlist, $settimeflag->temp_map_column_id, ['empty'=>'--Select--','required' => true,'class'=>'form-control']) !!}

                                    @error('temp_map_column_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="settime" class="col-md-3 col-form-label text-md-right">{{ __('Set Time (HH:00) Ex. 02:00 ') }}</label>

                                <div class="col-md-6">
                                    <input id="settime" type="text" class="form-control @error('settime') is-invalid @enderror"
                                        name="settime" value="00:00" required autofocus>

                                    @error('settime')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="flag" class="col-md-3 col-form-label text-md-right">{{ __('Flag') }}</label>

                                <div class="col-md-6">
                                    <input id="flag" type="text" class="form-control @error('flag') is-invalid @enderror"
                                        name="flag" value="{{ $settimeflag->flag }}" required autofocus>

                                    @error('flag')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="desc" class="col-md-3 col-form-label text-md-right">{{ __('รายละเอียด') }}</label>

                                <div class="col-md-6">
                                    <input id="desc" type="text" class="form-control @error('desc') is-invalid @enderror"
                                        name="desc" value="{{ $settimeflag->desc }}" required autofocus>

                                    @error('desc')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-6">
                                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror"
                                        name="status" value="Active" autofocus>

                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('สร้าง') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qc/set_time_flags/create.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Flag Time') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('set_time_flags.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('สร้าง Column Map') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('set_time_flags.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="temp_map_column_id" class="col-md-3 col-form-label text-md-right">{{ __('Sensor') }}</label>

                                <div class="col-md-6">
                                    {!! Form::select('temp_map_column_id', $tempmapcolumnlist, null, ['placeholder'=>'--Select--','class'=>'form-control']) !!}

                                    @error('temp_map_column_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="sensor_id" class="col-md-3 col-form-label text-md-right">{{ __('Sensor RTE') }}</label>

                                <div class="col-md-6">
                                    {!! Form::select('sensor_id', $sensorlist, null, ['placeholder'=>'--Select--','class'=>'form-control']) !!}

                                    @error('sensor_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="settime" class="col-md-3 col-form-label text-md-right">{{ __('Set Time (HH:00) Ex. 02:00 ') }}</label>

                                <div class="col-md-6">
                                    <input id="settime" type="text" class="form-control @error('settime') is-invalid @enderror"
                                        name="settime" value="" required autofocus>

                                    @error('settime')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="flag" class="col-md-3 col-form-label text-md-right">{{ __('Flag') }}</label>

                                <div class="col-md-6">
                                    <input id="flag" type="text" class="form-control @error('flag') is-invalid @enderror"
                                        name="flag" value="" required autofocus>

                                    @error('flag')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="desc" class="col-md-3 col-form-label text-md-right">{{ __('รายละเอียด') }}</label>

                                <div class="col-md-6">
                                    <input id="desc" type="text" class="form-control @error('desc') is-invalid @enderror"
                                        name="desc" value="" required autofocus>

                                    @error('desc')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-6">
                                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror"
                                        name="status" value="Active" autofocus>

                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('สร้าง') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qc/set_time_flags/edit.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Flag Time') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('set_time_flags.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แก้ไข Column Map กับ Excel Scada') }}</div>

                    <div class="card-body">
                        <form action="{{ route('set_time_flags.update', $settimeflag->id) }}" method="POST">
                            @csrf

                            @method('PUT')
                            
                            <div class="form-group row">
                                <label for="temp_map_column_id" class="col-md-3 col-form-label text-md-right">{{ __('Sensor') }}</label>

                                <div class="col-md-6">
                                    {!! Form::select('temp_map_column_id', $tempmapcolumnlist, $settimeflag->temp_map_column_id, ['placeholder'=>'--Select--','class'=>'form-control']) !!}

                                    @error('temp_map_column_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="sensor_id" class="col-md-3 col-form-label text-md-right">{{ __('Sensor RTE') }}</label>

                                <div class="col-md-6">
                                    {!! Form::select('sensor_id', $sensorlist, $settimeflag->sensor_id, ['placeholder'=>'--Select--','class'=>'form-control']) !!}

                                    @error('sensor_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="settime" class="col-md-3 col-form-label text-md-right">{{ __('Set Time (HH:00) Ex. 02:00 ') }}</label>

                                <div class="col-md-6">
                                    <input id="settime" type="text" class="form-control @error('settime') is-invalid @enderror"
                                        name="settime" value="{{ $settimeflag->settime }}" required autofocus>

                                    @error('settime')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="flag" class="col-md-3 col-form-label text-md-right">{{ __('Flag') }}</label>

                                <div class="col-md-6">
                                    <input id="flag" type="text" class="form-control @error('flag') is-invalid @enderror"
                                        name="flag" value="{{ $settimeflag->flag }}" required autofocus>

                                    @error('flag')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="desc" class="col-md-3 col-form-label text-md-right">{{ __('รายละเอียด') }}</label>

                                <div class="col-md-6">
                                    <input id="desc" type="text" class="form-control @error('desc') is-invalid @enderror"
                                        name="desc" value="{{ $settimeflag->desc }}" required autofocus>

                                    @error('desc')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="status" class="col-md-3 col-form-label text-md-right">{{ __('Status') }}</label>

                                <div class="col-md-6">
                                    <input id="status" type="text" class="form-control @error('status') is-invalid @enderror"
                                        name="status" value="{{ $settimeflag->status }}" autofocus>

                                    @error('status')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-3">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('แก้ไข') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/qc/set_time_flags/index.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการ Flag Time') }}</h3>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a class="btn btn-success" href="{{ route('set_time_flags.create') }}">สร้าง Flag Time</a>
                    </div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif
                            <div class="pagination-wrapper"> {!! $settimeflags->render('vendor\pagination\bootstrap-4') !!} </div>
                   
                        <table class="table table-bordered">
                            <tr>
                                <th>Sensor / Sensor RTE</th>
                                <th>เวลา</th>
                                <th>Flag</th>
                                <th>สถานะ</th>
                                <th></th>
                            </tr>
                            @foreach ($settimeflags as $settimeflag)
                                <tr>
                                    <td>{{ $settimeflag->tempmapcolumn->mapcolumn ?? '-' }} / {{ $settimeflag->sensor->coil ?? '-' }} </td>
                                    <td>{{ $settimeflag->settime }}</td>
                                    <td>{{ $settimeflag->flag }}</td>
                                    <td>{{ $settimeflag->status }}</td>
                                    <td>
                                        <a class="btn btn-info" href="{{ route('set_time_flags.show', $settimeflag->id) }}">แสดง</a>
                                        <a class="btn btn-primary" href="{{ route('set_time_flags.edit', $settimeflag->id) }}">แก้ไข</a>
                                        <a class="btn btn-secondary" href="{{ route('set_time_flags.clone', $settimeflag->id) }}">clone</a>
                                        <form action="{{ route('set_time_flags.destroy', $settimeflag->id) }}" method="POST">

                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">ลบ</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                         <div class="pagination-wrapper"> {!! $settimeflags->render('vendor\pagination\bootstrap-4') !!} </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection

resources/views/qc/set_time_flags/view.blade.php
@extends('layouts.main')

@section('content')

    <div class="page-heading">
        <h3>{{ __('จัดการประเภทกล่องแตก') }}</h3>
        <div class="pull-right">
            <a class="btn btn-success" href="{{ route('temp_map_columns.index') }}">Back</a>
        </div>
    </div>
    <div class="page-content">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">{{ __('แสดงประเภทกล่องแตก') }}</div>

                    <div class="card-body">
                        @if ($message = Session::get('success'))
                            <div class="alert alert-success">
                                <p>{{ $message }}</p>
                            </div>
                        @endif

                        <table class="table table-bordered">
                            <tr>
                                <th>ชื่อ</th>
                                <td>{{ $tempmapcolumn->name }}</td>
                            </tr>
                            <tr>
                                <th>Displayname</th>
                                <td>{{ $tempmapcolumn->displayname }}</td>
                            </tr>
                            <tr>
                                <th>Map Column</th>
                                <td>{{ $tempmapcolumn->mapcolumn }}</td>
                            </tr>
                            <tr>
                                <th>Type Column</th>
                                <td>{{ $tempmapcolumn->typecolumn }}</td>
                            </tr>
                            <tr>
                                <th>Show</th>
                                <td> <div class="col-md-6">
                                    {{ Form::select('show', array('Yes'=>'Yes','No'=>'No'), $tempmapcolumn->show, ['placeholder' => '==เลือก==', 'class' => 'form-control']) }}                                    
                            </tr>
                            <tr>
                                <th>Seq</th>
                                <td>{{ $tempmapcolumn->seq }}</td>
                            </tr>
                            <tr>
                                <th>Condition</th>
                                <td>{{ $tempmapcolumn->conditions }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>{{ $tempmapcolumn->status }}</td>
                            </tr>
                            
                            <tr>
                                <th>Action</th>
                                <td>
                                    <a class="btn btn-primary" href="{{ route('temp_map_columns.edit', $tempmapcolumn->id) }}">แก้ไข</a>
                                    <form action="{{ route('temp_map_columns.destroy', $tempmapcolumn->id) }}" method="POST">

                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">ลบ</button>
                                    </form>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>




@endsection