routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TempMapColumnsController;
use App\Http\Controllers\SetTimeFlagsContoller;
use App\Http\Controllers\UserController;
use App\Http\Controllers\TempsController;
use App\Http\Controllers\SensorsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::prefix('qc')->group(function () {
    Route::resource('temp_map_columns', TempMapColumnsController::class);
    Route::resource('temps', TempsController::class);
    Route::resource('sensors', SensorsController::class);
    Route::get('temps/excel/{date}', [TempsController::class, 'excel'])->name('temps.excel');
    Route::resource('set_time_flags', SetTimeFlagsContoller::class);
    Route::get('set_time_flags/clone/{id}', [SetTimeFlagsContoller::class, 'clone'])->name('set_time_flags.clone');
});
Route::resource('user', UserController::class);


Route::group(['namespace' => 'App\Http\Controllers'], function()
{   
    /**
     * Home Routes
     */
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::group(['middleware' => ['guest']], function() {
        /**
         * Register Routes
         */
        Route::get('/register', 'RegisterController@show')->name('register.show');
        Route::post('/register', 'RegisterController@register')->name('register.perform');

        /**
         * Login Routes
         */
        Route::get('/login', 'LoginController@show')->name('login.show');
        Route::post('/login', 'LoginController@login')->name('login.perform');

    });

    Route::group(['middleware' => ['auth']], function() {
        /**
         * Logout Routes
         */
        Route::get('/logout', 'LogoutController@perform')->name('logout.perform');
    });
});

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LACO - WH Loading System</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.css') }}">

    <link rel="stylesheet" href="{{ asset('assets/vendors/iconly/bold.css') }}">

    <link rel="stylesheet" href="{{ asset('assets/vendors/perfect-scrollbar/perfect-scrollbar.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendors/bootstrap-icons/bootstrap-icons.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/app.css') }}">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="shortcut icon" href="{{ asset('assets/images/favicon.svg') }}" type="image/x-icon">
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header">
                    <div class="d-flex justify-content-between">
                        <div class="logo">
                            <a href="{{ url("/") }}"><img src="{{ asset('logo/laco_logo.png') }}" alt="Logo" srcset=""></a>
                        </div>
                        <div class="toggler">
                            <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                     @include('layouts.menu')
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            </div>
        </div>
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block d-xl-none">
                    <i class="bi bi-justify fs-3"></i>
                </a>
            </header>


            @yield('content')


            <footer>
                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                        <p>2021 &copy; LACO</p>
                    </div>
                    <div class="float-end">
                        <p>Develop By LACO IT</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="{{ asset('assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
    <script src="{{ asset('assets/js/bootstrap.bundle.min.js') }}"></script>

    <script src="{{ asset('assets/vendors/apexcharts/apexcharts.js') }}"></script>
    <script src="{{ asset('assets/js/pages/dashboard.js') }}"></script>

    <script src="{{ asset('assets/js/main.js') }}"></script>
</body>

</html>

resources/views/layouts/menu.blade.php
<ul class="menu">

    @if (Auth::guest())
        <li class="sidebar-item active ">
            <a href="{{ route('login.perform') }}" class='sidebar-link'>
                <i class="bi bi-grid-fill"></i>
                <span>Login</span>
            </a>
        </li>
    @else
        <li class="sidebar-item">
            {{ Auth::user()->name }}
        </li>
        <li class="sidebar-item">
            <a href="{{ route('user.index') }}" class='sidebar-link'>
                <i class="bi bi-grid-fill"></i>
                <span>User</span>
            </a>
        </li>
        <li class="sidebar-item">
            <a href="{{ route('temp_map_columns.index') }}" class='sidebar-link'>
                <i class="bi bi-grid-fill"></i>
                <span>จัดการ Column Map กับ Excel Scada</span>
            </a>
        </li>
        <li class="sidebar-item">
            <a href="{{ route('sensors.index') }}" class='sidebar-link'>
                <i class="bi bi-grid-fill"></i>
                <span>จัดการ Sensor กับ Flex Scada</span>
            </a>
        </li>
        <li class="sidebar-item">
            <a href="{{ route('set_time_flags.index') }}" class='sidebar-link'>
                <i class="bi bi-grid-fill"></i>
                <span>จัดการ Flag Time</span>
            </a>
        </li>

        <li class="sidebar-item">
            <a href="{{ route('temps.index') }}" class='sidebar-link'>
                <i class="bi bi-grid-fill"></i>
                <span>ข้อมูลอุณหภูมิ</span>
            </a>
        </li>

        
        <li class="sidebar-item">
            <a href="{{ route('logout.perform') }}">Logout</a>
        </li>

        {{-- <li class="sidebar-item  has-sub">
            <a href="#" class='sidebar-link'>
                <i class="bi bi-stack"></i>
                <span>รายงาน</span>
            </a>
            <ul class="submenu ">
                <li class="submenu-item ">
                    <a href="{{ url('/reports/exportdata') }}">Exports</a>
                </li>
            </ul>
        </li>
        @guest

        @else 
        
                <li class="sidebar-item ">
                    <a  class='sidebar-link' href="#">Change Pass</a>
                </li>
        <li class="sidebar-item">
            <!-- Authentication -->
            <form method="POST" action="{{ route('logout') }}">
                @csrf
                <a  class='sidebar-link' href="{{ route('logout') }}" onclick="event.preventDefault();
                        this.closest('form').submit();">
                    {{ __('Logout') }}
                </a>
            </form>
        </li>
        @endguest--}}
        
        
    @endif
</ul>